// <auto-generated />
using System;
using Demo_WebAPI_EventAgenda.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo_WebAPI_EventAgenda.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218151332_update3")]
    partial class update3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo_WebAPI_EventAgenda.Domain.Models.AgendaEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Category_Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Desc")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("End Date");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("Start Date");

                    b.HasKey("Id")
                        .HasName("PK_Agenda_Events");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Category_Id");

                    b.HasIndex("Name", "Location", "StartDate")
                        .IsUnique()
                        .HasDatabaseName("IDX_Agenda_Events__Name_Loc_Date")
                        .HasFilter("[Location] IS NOT NULL");

                    b.ToTable("Agenda_Events", (string)null);
                });

            modelBuilder.Entity("Demo_WebAPI_EventAgenda.Domain.Models.EventCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Event_Categories_Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IDX_Event_Categories__Name")
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Event_Categories", (string)null);
                });

            modelBuilder.Entity("Demo_WebAPI_EventAgenda.Domain.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Answer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit")
                        .HasColumnName("IsVisible");

                    b.Property<int>("NbLikes")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Question");

                    b.HasKey("Id")
                        .HasName("PK_FAQs");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Question")
                        .HasDatabaseName("IDX_FAQs_Question");

                    b.ToTable("FAQs", (string)null);
                });

            modelBuilder.Entity("Demo_WebAPI_EventAgenda.Domain.Models.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowNewsletter")
                        .HasColumnType("bit")
                        .HasColumnName("AllowNewsletter");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("Email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Pseudonyme")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Pseudonyme");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Role");

                    b.HasKey("Id")
                        .HasName("PK_Members");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IDX_Members__Email");

                    b.HasIndex("Pseudonyme")
                        .IsUnique()
                        .HasDatabaseName("IDX_Members_Pseudonyme")
                        .HasFilter("[Pseudonyme] IS NOT NULL");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("Demo_WebAPI_EventAgenda.Domain.Models.AgendaEvent", b =>
                {
                    b.HasOne("Demo_WebAPI_EventAgenda.Domain.Models.EventCategory", "Category")
                        .WithMany()
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Agenda_Events_Event__Categories");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
